### ISSUE TITLE
Parameterized static directory

### ISSUE THREAD

**Issue by elwin013** [elwin013/parcel-plugin-static-files-copy#1]
Path to directory with static files should be possible to parameterize (instead of hardcoded `static` directory).

**Comment by apvarun** [comment]
I can work on this enhancement

**Comment by elwin013** [comment]
@apvarun Great job! I will review code as soon as possible :)

**Comment by elwin013** [comment]
@apvarun Reviewed and merged. Thank you for your contribution. :-)
