### ISSUE TITLE
parcel-plugin-static-files-copy not work

### ISSUE THREAD

**Issue by zababurinsv** [elwin013/parcel-plugin-static-files-copy#111]
I install all packages.
```
  "devDependencies": {
    "@babel/preset-react": "^7.14.5",
    "@parcel/resolver-default": "^2.0.0-alpha.3",
    "@parcel/transformer-sass": "2.0.0-rc.0",
    "npm-run-all": "^4.1.5",
    "parcel": "2.0.0-rc.0",
    "parcel-plugin-static-files-copy": "^2.6.0",
    "terser": "^5.9.0"
  }
```

Add in package.json from manual path

```
  "staticFiles": {
    "staticPath": "./public",
    "watcherGlob": "**"
  },
```

add in root public path.

But static file not to copy to dist dir.

What do i wrong ?

**Comment by elwin013** [comment]
Hey @zababurinsv. I can see that you use Parcel 2 (`2.0.0-rc.0`). Parcel 2 has different plugin system and there is another plugin for it - https://github.com/elwin013/parcel-reporter-static-files-copy
