### ISSUE TITLE
Icon not copied to dist after updating Parcel to v2 

### ISSUE THREAD

**Issue by tristanpendergrass** [elwin013/parcel-plugin-static-files-copy#113]
Hello, first let me say that this plugin has been very useful to me since I started using it for my personal projects over the last year. Always does its job with no fuss or problems. Until now! :)

More detail below, but the core issue is: when I run `npm start` in [this repo](https://github.com/tristanpendergrass/shiny-meme) the `/dist` generated includes only some of the assets from my /static directory. It seems that it includes e.g. the favicon.png but not the forest.png, and this is presumably because favicon is referenced from the index.html whereas forest.png is referenced only in a .elm file. This issue started happening when I updated some dependencies (although not when I updated parcel-plugin-static-files-copy itself).

![image](https://user-images.githubusercontent.com/4894672/144755877-e679ac39-4e27-4ba0-8101-e3703ef93d73.png)

I first noticed the issue after I recently [updated](https://github.com/tristanpendergrass/elm-empty-project/commit/8ea059dc47aa503a9cba2325bf464d0f7fef962f) a bunch of dependencies in my template for my projects. The change I believe is relevant to this issue was moving from using my globally installed Parcel (which I believe was v1?) to a locally installed parcel set to 2.0. I did not update the parcel-plugin-static-files-copy dependency. I'm sure that before I did this parcel-plugin-static-files-copy was working as I expected: copying all the files in /static into dist, even if they were only referenced in a .elm file.

I have tried updating parcel-plugin-static-files-copy to its latest version (^2.6.0) and it did not help.

I have tried using both parcel-plugin-static-files-copy and parcel-reporter-static-files-copy (I'm not sure what the difference is supposed to be but both had identical results for me).

Any help would be greatly appreciated.

**Comment by elwin013** [comment]
Hello @tristanpendergrass. This plugin (`parcel-plugin-static-files-copy`) is for Parvel v1. For Parcel v2 you need to use [parcel-reporter-static-files-copy](https://github.com/elwin013/parcel-reporter-static-files-copy).

The most important change between Parcel v1 and v2 is that you need to configure Parcel to use plugin - please see Usage section of [v2 plugin Readme](https://github.com/elwin013/parcel-reporter-static-files-copy#usage) (screenshot below).

![readme section of plugin](https://user-images.githubusercontent.com/375909/144825972-731a27be-1b17-4357-95ca-6c25429a2c4d.png)

I've looked briefly over the links you posted and looks like it is the case - Parcel v2 and plugin for v1. :-)
