### ISSUE TITLE
Watching fails randomly after Nth file change

### ISSUE THREAD

**Issue by duzenko** [elwin013/parcel-plugin-static-files-copy#135]
I have this problem that I have to often modify the source files that should be watched and overwritten by this package.
Rather frustratingly, after a few overwrites further edits don't appear to trigger new overwrites.
No errors/warnings in the output that I can see.
What could be causing it?
FWIW the file system is NTFS, and the debug server is `parcel serve src/index.html`

**Comment by duzenko** [comment]
Just one observation
After `parcel serve` restart, it seems to notice that files are different and does overwrite it. Then it works for a short time and stops watching again.

**Comment by elwin013** [comment]
Parcel v1 is not maintained anymore - there will be no further development of this plugin, but some bug fixes (if any). 

Thank you all for your contributions! :smile:
