### ISSUE TITLE
Actually copy the folder.

### ISSUE THREAD

**Issue by antonedvard** [elwin013/parcel-plugin-static-files-copy#14]
Seems like the actual folder is not copied over to the dist folder? the plugin only grabs the content of the folder and throws them in the root of the dist folder...

Any possibility to input more options into the plugin to configure this, perhaps set a flag in package.js to be able to grab the whole folder and not just the content...?

**Comment by elwin013** [comment]
Hello @antonedvard! I see that you opened and closed issue in very short time. Does problem is solved? 

I checked it right now and plugin copies files and not empty folders - I think that's right way to do.

**Comment by antonedvard** [comment]
Hei buddy, yeah, the issue was that I defined my own folders in the package.json file for the static folders, and when i did that he only copied the content of the folder and not the folder itself,
i just had to move the statics folder out of the src folder and down to root of my project and then create a new folder inside that static folder with the folder that was supposed to contain my files...
