### ISSUE TITLE
Can't get staticPath as array working

### ISSUE THREAD

**Issue by goldingdamien** [elwin013/parcel-plugin-static-files-copy#147]
Non-array works:

```
{
 "staticFiles": {
    "staticPath": "public"
  }
}
```

Array causes "TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received an instance of Array" error:

```
{
 "staticFiles": {
    "staticPath": ["public"]
  }
}
```
 
 What is the problem?

**Comment by elwin013** [comment]
Hi @goldingdamien!
Everything looks ok on the side of the plugin - when running [this example](https://github.com/elwin013/parcel-plugin-static-files-copy/tree/master/examples/multiple-staticpath) all seems to be ok.

Could you provide some minimal reproducible example project? Also information about OS, Node version will be also appreciated.

**Comment by wallabyway** [comment]
nope.  it still does not work.

same error as [goldingdamien](https://github.com/goldingdamien) reported

All we want to do is copy 4 files, to the dest folder.  That's it.  Using an array, as specified in the docs, does not work and causes the error mentioned above.

package.json
```
  "devDependencies": {
    "parcel-reporter-static-files-copy": "^1.5.2",
    "parcel": "^2.9.3"
etc

  "staticFiles": {
    "staticPath": [
      "node_modules/@shoelace-style/shoelace/dist/assets/icons/camera-reels.svg",
      "node_modules/@shoelace-style/shoelace/dist/assets/icons/diagram-3.svg",
      "node_modules/@shoelace-style/shoelace/dist/assets/icons/file-ruled.svg",
      "node_modules/@shoelace-style/shoelace/dist/assets/icons/gear.svg"
     ],
    "staticOutPath": "assets/icons"
  }  
```

.parcelrc
```
{
  "extends": ["@parcel/config-default"],
  "reporters":  ["...", "parcel-reporter-static-files-copy"]
}
```

**Comment by elwin013** [comment]
Provided example explains everything :-)

You are using the Parcel v2 and plugin for it - repository for that plugin is [parcel-reporter-static-files-copy](https://github.com/elwin013/parcel-reporter-static-files-copy).

And for this (newer) plugin the correct configuration to copy multiple (single) files is:

```json
  "staticFiles": [
    {
      "staticPath": "static.txt"
    },
    {
      "staticPath": "static2.txt"
    }
  ]
```

Where `staticPath` can be file or directory. This will be use case for @goldingdamien.

In the second case - @wallabyway - you need to add `staticOutPath` to every config entry, so it will be:

```json
  "staticFiles": [
    {
      "staticPath": "static.txt",
      "staticOutPath": "outDir"
    },
    {
      "staticPath": "static2.txt",
      "staticOutPath": "outDir"
    }
```

It will work correctly from [v1.5.3](https://www.npmjs.com/package/parcel-reporter-static-files-copy/v/1.5.3) of the plugin - already pushed to NPM registry.

**Comment by dabico** [comment]
Forgive me for excavating this long-closed issue. I think the README contains outdated information, and as such you may want to update it to reflect the previous comment. I faced the same problem as Damien. I configured the plugin like he did, which is what the README instructs. It was only by chance I found your explanation and corrected the error as instructed. Other people are likely to stumble into the same issue, and not all of them may find this issue.

**Comment by elwin013** [comment]
Hi @dabico! No problem at all! :smile: 

Based on information that you provide seems that you are using new Parcel (v2, 2.x) available in NPM registry under name `parcel`. And this repository is a plugin for old Parcel (v1, 1.x) available in registry under name `parcel-bundler`. 

In the README there is note that (at top):

> Looking for the ParcelV2 plugin? Check out [parcel-reporter-static-files-copy](https://github.com/elwin013/parcel-reporter-static-files-copy)

which redirects to the plugin for the Parcel v2.
