### ISSUE TITLE
Constant rebuilds in Windows

### ISSUE THREAD

**Issue by xphstos** [elwin013/parcel-plugin-static-files-copy#16]
While the plugin works perfectly on my Mac, in my windows machine is causing parcel-bundler to rebuild infinitely.
It keeps overriding the static files in "dist" folder.
I think it happens because the below statement always evaluates truthy.

``` 
if (destStat.mtime <= srcStat.mtime) {
  // File was modified - let's copy it and inform about overwriting.
  console.info( `Info: Static file '${filepath}' do already exist in '${bundleDir}'. Overwriting.`)
  fs.copyFile(filepath, dest)
}
```

After logging the timestamps I found out that if I don't made any changes to my static files the timestamps match, being equal they overwrite the files causing the rebuild.
My quick fix was to remove the "=".
Although I don't know what kind of re-precautions this would cause in other OS.

``` 
if (destStat.mtime < srcStat.mtime) {
  // File was modified - let's copy it and inform about overwriting.
  console.info( `Info: Static file '${filepath}' do already exist in '${bundleDir}'. Overwriting.`)
  fs.copyFile(filepath, dest)
}
```

**Comment by elwin013** [comment]
Should be closed by #15. Please reopen if problem still occurs
