### ISSUE TITLE
Dev or Production config?

### ISSUE THREAD

**Issue by maximelebreton** [elwin013/parcel-plugin-static-files-copy#17]
Hello,
Is it possible to have a dev and production config?

Thanks!

**Comment by dotterian** [comment]
I'll add to this request.
It would be great to have environment-dependent folders, that would look something like this in config:
```json
{
  "staticFiles": {
    "staticPath": ["src/assets"],
    "env": {
      "beta": ["src/beta-assets"],
      "producton": ["src/production-assets"]
    }
  }
}
```

In my case there are different `robots.txt` for production and beta and I would rather resolve this problem using tools that I already use than add additional steps to my continuous delivery config.

**Comment by elwin013** [comment]
@dotterian, @maximelebreton Will look into this in next few days.

**Comment by kahurangitama** [comment]
Is there a way to set output folder e.g. put all assets into dist/static for example?

**Comment by elwin013** [comment]
Ok, few days turns to "a lot of days". I'll review MR #22 (issue #21), then go with that. 

It will look (probably) like this in configuration (that will put files from `static1` in dist folder when `env == production`:

```
{
  "staticPath": "static1",
  "env": "production"
},
```

**Comment by elwin013** [comment]
@kahurangitama Right now - no. You have to create directory tree for that (like `static/static` and it will be put as `dist/static`).

**Comment by dotterian** [comment]
Hi, @elwin013, any progress on this issue?

**Comment by elwin013** [comment]
@dotterian Fixed some other issue, this will be next. ;-)

**Comment by elwin013** [comment]
With version 2.4.0 there is possible to "select" static path based on `NODE_ENV`.  Configuration as mentioned above:
```
{
  "staticPath": "static1",
  "env": "production"
},
``` 
where `env` is environment passed via `NODE_ENV`.
Additional example is in readme and in examples directory.
