### ISSUE TITLE
Does not work when there are multiple entry points

### ISSUE THREAD

**Issue by openjck** [elwin013/parcel-plugin-static-files-copy#18]
Parcel allows the developer to specify multiple entrypoints. For example:

```
parcel build src/index.html src/404.html
```

When this is done, parcel-plugin-static-files-copy fails with an error on [line 8 of index.js](https://github.com/elwin013/parcel-plugin-static-files-copy/blob/70b2de868537774005ee063dc5622bd9671b6166/index.js#L8).

**Comment by elwin013** [comment]
Should be closed by #15. Please reopen if problem still occurs

**Comment by openjck** [comment]
That worked perfectly. Thanks to you and @doconix.
