### ISSUE TITLE
Is it possible to set target folder?

### ISSUE THREAD

**Issue by simensol** [elwin013/parcel-plugin-static-files-copy#19]
Is it possible to set target folder(s), like:

``
staticPath: {
    "source": "['/source/dir','/source/static']",
    "target": "['/target/dir','/target/static']"
  },
``

in [parcel-plugin-copy](https://www.npmjs.com/package/parcel-plugin-copy)?

**Comment by elwin013** [comment]
@simensol you mean that:
* `/source/dir` will go to `/target/dir`
* `/source/static` will go to `/target/static`

?

If yes - you can create just one directory `source` with directories `dir` and `static` - both subdirectories will be copied.

**Comment by simensol** [comment]
@elwin013 Currently, all files/folders in the `staticPath` are copied to the `js` directory of my output directory, e.g. `build/js`. However, I want to copy files/folders in `static/js` to `build/js` and files/folders in `static/css` to `build/css` etc.

**Comment by elwin013** [comment]
@simensol Can you prepare/show some configuration?

**Comment by elwin013** [comment]
Ah, ok, got it! Right now it is not possible.

**Comment by ryanwinchester** [comment]
Right now, I have:

```json
{
  "scripts": {
    "deploy": "parcel build js/app.js css/app.css --out-dir ../priv/static",
    "watch": "parcel watch js/app.js css/app.css --out-dir ../priv/static"
  },
  "staticFiles": {
    "staticPath": "static",
    "watcherGlob": false
  },
}
```

I have `source`:
```
js/app.js
css/app.css
static/images/
```

I want `target` to be:
```
priv/static/js/app.js
priv/static/css/app.css
priv/static/images/
```

But I end up with images in `priv/static/js/images/`
