### ISSUE TITLE
How to load static CSS files in parcel

### ISSUE THREAD

**Issue by edelhart-voicebase** [elwin013/parcel-plugin-static-files-copy#20]
I realize this isn't "Your problem" but -- I want to load a css file as a static resource without it being parsed by parcel (which has a problem with the css that antD generates for some reason) --- but if I include the link to the file (that I provide as a static resource) Parcel's bundler chokes because it can't find it at build time.

**Comment by elwin013** [comment]
@edelhart-voicebase Hm.. doesn't have need like this. Will look into it

**Comment by edelhart-voicebase** [comment]
Thanks -- if you need a concrete scenario -- /static/style.css combined with <link href="/style.css">

**Comment by stoically** [comment]
@edelhart-voicebase If it's a html file you're putting the css link into, then maybe [parcel-plugin-html-externals](https://github.com/stoically/parcel-plugin-html-externals) could be of use.

**Comment by elwin013** [comment]
@edelhart-voicebase A plugin provided by @stoically could do the job, can you confirm?

**Comment by elwin013** [comment]
Looks like  [parcel-plugin-html-externals](https://github.com/stoically/parcel-plugin-html-externals) should do the trick. Closing then. :-)
