### ISSUE TITLE
Different static file configurations for different entrypoint or dist directory?

### ISSUE THREAD

**Issue by uglycoyote** [elwin013/parcel-plugin-static-files-copy#21]
I have a setup where I am have one repo where I have multiple entry points.  I want to package up each entry point's dependencies separately, and therefore I build each entry point to a different output directory.   When using this plugin, the same set of static files end up in each dist directory.  I would like it if I can configure it somehow to copy a different set of static files depending on either which entrypoint I am building, or which dist directory I'm building to.  

(Currently I'm building one entrypoint which is a big heavy weight thing which requires *all* of the static files, and another entrypoint requires *none* of the static files, but those details are not too important to my question.)

Is there currently a way to do this?

**Comment by elwin013** [comment]
Merged #22, closing.

@uglycoyote thank you for your contribution!
