### ISSUE TITLE
Latest release and parcel watch

### ISSUE THREAD

**Issue by sbmw** [elwin013/parcel-plugin-static-files-copy#23]
Hey

The latest release (with pull 22) seems to have affected parcel watch functionality.

Subsequent build messages are listed on new lines, such as:

✨  Built in 2.26s.
✨  Built in 6.45s.
✨  Built in 1.16s.
config.staticPath after handling conditionals: static

I assume this is due to the staticPath message adding a new line that the parcel cli doesn't know to delete.

This on it's own is trivial, but for some reason (I assume connected) this has also stopped automatic page reloads on each incremental build.

**Comment by sbmw** [comment]
In fact, yes, removing the following line resolves both issues:

console.log(`config.staticPath after handling conditionals: ${config.staticPath}`);

**Comment by elwin013** [comment]
@sbmw Hello, Thank you for reporting this. Will release fix today

**Comment by elwin013** [comment]
@sbmw should be fixed in 2.1.1 version (published to npm)

**Comment by sbmw** [comment]
@elwin013 Amazing!  Confirmed fixed in 2.1.1.

**Comment by elwin013** [comment]
@sbmw Yay! Thank you for confirming! :-)

**Comment by uglycoyote** [comment]
@elwin013 thanks for fixing, and sorry for causing this issue.  Any reason you know why the extra prints would have caused auto-reloads not to work?  that seems strange.
