### ISSUE TITLE
Replace 'file-system' with native 'fs' NodeJS API

### ISSUE THREAD

**Issue by elwin013** [elwin013/parcel-plugin-static-files-copy#3]
Less dependencies is always better. ;-)

**Comment by ChrisAckerman** [comment]
No, that is not a true statement :P. Especially when the dependency is well used like `file-system` is.

**Comment by apvarun** [comment]
I would also suggest to keep the dependency as it's a build time dependency. Also if we were to replace this with native APIs, that would be at the cost of users having to update their node versions.

@ChrisAckerman, would you mind explaining your reason here ?

**Comment by elwin013** [comment]
@ChrisAckerman But it is not 'false' either. ;-) I want to do it because number of dependencies in `node_modules` is really big, which is not good at all..

**Comment by elwin013** [comment]
Not important at all, closing. :-)
