### ISSUE TITLE
Different source of static files based on output directory issue

### ISSUE THREAD

**Issue by pivanov** [elwin013/parcel-plugin-static-files-copy#32]
Based on #21 
my package.json looks like this:
```
{
  ...,
  "staticFiles": {
    "staticPath": [
      {
        "outDirPattern": "**/dist-1",
        "staticPath": "static/dist-1"
      },
      {
        "outDirPattern": "**/dist-2",
        "staticPath": "static/dist-2"
      }
    ]
  }
}
```

The plugin works fine and copy the right files inside right places but I receive the following warnings:
`outDir matches '**/dist-1' so copying static files from 'static/dist-1'`
`outDir matches '**/dist-2' so copying static files from 'static/dist-2'`

Hope this will help

**Comment by elwin013** [comment]
hey @pivanov, if everything works well then it is expected behavior ;-) 

Please look here into documentation of Parcel about logging (here - https://parceljs.org/cli.html#change-log-level). This plugin is logging on level 3 (so 3 and above). :-)
