### ISSUE TITLE
This plugin won't serve any file which without a suffix name

### ISSUE THREAD

**Issue by yingshaoxo** [elwin013/parcel-plugin-static-files-copy#37]
```
age_gender_model-shard1
age_gender_model-weights_manifest.json
face_expression_model-shard1
face_expression_model-weights_manifest.json
face_landmark_68_model-shard1
face_landmark_68_model-weights_manifest.json
face_landmark_68_tiny_model-shard1
face_landmark_68_tiny_model-weights_manifest.json
face_recognition_model-shard1
face_recognition_model-shard2
face_recognition_model-weights_manifest.json
mtcnn_model-shard1
mtcnn_model-weights_manifest.json
ssd_mobilenetv1_model-shard1
ssd_mobilenetv1_model-shard2
ssd_mobilenetv1_model-weights_manifest.json
tiny_face_detector_model-shard1
tiny_face_detector_model-weights_manifest.json
```

If I visit `http://localhost:1234/weights/tiny_face_detector_model-shard1`, nothing will be downloaded, and nothing will show up.

But if I visit `tiny_face_detector_model-weights_manifest.json`, I can see the JSON file instantly.

___

You can download those files in here:

https://github.com/justadudewhohacks/face-api.js/tree/master/weights

**Comment by stoically** [comment]
It's not the plugin serving the files, but parcel itself.

**Comment by elwin013** [comment]
Yes, this is behavior of Parcel and looks like intended, please see [code](https://github.com/parcel-bundler/parcel/blob/v2/packages/reporters/dev-server/src/Server.js#L121) and discussion [here](https://github.com/parcel-bundler/parcel/pull/974#discussion_r173627321).

Closing this issue as nothing cannot be done from plugin perspective.
