### ISSUE TITLE
Create Folder if not exists

### ISSUE THREAD

**Issue by windischb** [elwin013/parcel-plugin-static-files-copy#39]
Hi!

Is it possible to create the Output folder if it doesn't exists?
```json
"staticFiles": {
    "staticPath": [
      {
        "staticPath": "assets",
        "staticOutDir": "assets"
      }
    ],
    "watcherGlob": "**"
  }
```
On a production build i use clean Docker Container for building. So there doesn't exist an "assets" folder...
Would be great if i don't have to create the folder by another Script.

Br
Bernhard

**Comment by windischb** [comment]
Sorry... 
Was my mistake, the folder is created automatically...

**Comment by elwin013** [comment]
No problem! ;-)
