### ISSUE TITLE
Parcel v2 support

### ISSUE THREAD

**Issue by nikolay-govorov** [elwin013/parcel-plugin-static-files-copy#41]
Hi. Thank you for your work.

Now we are working on the [second version of Parcel](https://github.com/parcel-bundler/parcel/issues/3377), with a redesigned plugin engine.

What do you think it will be difficult to update the plugin to work with the new version as well?

**Comment by MarkLyck** [comment]
yes 🙏 update this plugin for parcel@2.x

**Comment by nikolay-govorov** [comment]
Thanks

**Comment by elwin013** [comment]
@nikolay-govorov I think it is possible and not-so-difficult. I'll check this out as soon as possible. Sorry for not responding, many things gone crazy due to recent events.

**Comment by nikolay-govorov** [comment]
Hello. I apologize for my rudeness. I don't have much time to help you with pool requests, but I will be happy to help you test these changes on my project.

I would also be happy to support your project if you have a patreon or similar tool.

**Comment by bySabi** [comment]
@elwin013  Parcel 2 is not in beta please add Support

**Comment by Natetronn** [comment]
I would love to see this as well. Thank you!

**Comment by Natetronn** [comment]
I'm using Netlify, and it build image is Ubuntu, so I ended up using this for Parcel V2:

https://github.com/parcel-bundler/parcel/issues/1080#issuecomment-633119160

I modified mine slightly to use the static directory, like so:
```
  "postbuild": "cp -r static/* dist/",
```
Worked a treat!

**Comment by gmougeolle** [comment]
I've created a (very) simple plugin for those with a similar problem using Parcel v2 : https://github.com/gmougeolle/parcel-reporter-copystatic. So far it's very simple but PRs are welcome.

**Comment by elwin013** [comment]
First version of plugin for Parcel v2 is on github and npmjs:
* https://github.com/elwin013/parcel-reporter-static-files-copy
* https://www.npmjs.com/package/parcel-reporter-static-files-copy

Very, very big thanks for @gmougeolle who, by showing what is possible, made me to do this.
