### ISSUE TITLE
Stop logging "Static file '...' already exists in '...' . Overwriting.

### ISSUE THREAD

**Issue by maxstolze** [elwin013/parcel-plugin-static-files-copy#51]
Is it possible to stop logging "Static file '...' already exists in '...' . Overwriting." as it seems to be the expected behavior but logging it permanently while rebuilding?

**Comment by elwin013** [comment]
Hey @maxstolze!

At this moment this is expected behavior to log it while rebuilding. Please look [here](https://parceljs.org/cli.html#change-log-level) into documentation of Parcel about logging - this plugin is logging on level 3 (so 3 and above). :-)

**Comment by maxstolze** [comment]
Okay, so it's not an issue. Thank you!
