### ISSUE TITLE
use static resource in compiled code ?

### ISSUE THREAD

**Issue by koraysels** [elwin013/parcel-plugin-static-files-copy#52]
how do you use a resource from the static directory in your sourcecode?

e.g. I have an image in my static folder. I want to use it in my scss file..
what is the correct pattern ?

**Comment by elwin013** [comment]
Good question! I didn't have need like this yet ;-)

Will check and come back to you

**Comment by mateusvahl** [comment]
Any suggestions on this? 👀

**Comment by elwin013** [comment]
Parcel v1 is not maintained anymore - there will be no further development of this plugin, but some bug fixes (if any). 

Thank you all for your contributions! :smile:
