### ISSUE TITLE
Doesn't serve files without extensions

### ISSUE THREAD

**Issue by odbol** [elwin013/parcel-plugin-static-files-copy#65]
If you have a file without an extension in your public directory (e.g. `localhost:1234/ml/pitchDetection/group3-shard1of1`), it serves the index.html file instead.

**Comment by elwin013** [comment]
Hey @odbol!
This is known problem of ParcelJS, already reported here too (https://github.com/elwin013/parcel-plugin-static-files-copy/issues/37)

Please see [ParcelJS code](https://github.com/parcel-bundler/parcel/blob/v2/packages/reporters/dev-server/src/Server.js#L121) and discussion [here](https://github.com/parcel-bundler/parcel/pull/974#discussion_r173627321).

As stated in  #37 - nothing can be done on plugin side, so closing.
