### ISSUE TITLE
Feature Request: Add priority or conflict resolution to multiple static paths

### ISSUE THREAD

**Issue by TomJacobsUK** [elwin013/parcel-plugin-static-files-copy#66]
I'm currently using multiple static paths to combine two folders (local folder & folder from a package) into a single output directory. Using the local folder as an override to the packages folder, to the most part this works fine, provided that local directory files are newer than the package, as the plugin just checks the files modified time, this however causes issue when package is updated.

It would be useful to have the option to configure the plugins conflict resolution based on the order of static paths instead of just using the modified time.

Think this also partially links to #46 when watching files, as it only watches the latest file on init and requires a restart to watch the other file.

However this maybe unique use case that could be out of the scope of this plugin, if so let me know?
If not, I'll try my best to set some time aside to attempt come up with solution and make a pull request.

**Comment by elwin013** [comment]
Parcel v1 is not maintained anymore - there will be no further development of this plugin, but some bug fixes (if any). 

Thank you all for your contributions! :smile:
