### ISSUE TITLE
Another config source: CLI or separate file

### ISSUE THREAD

**Issue by Amaimersion** [elwin013/parcel-plugin-static-files-copy#69]
Hello! First of all, thank you for good plugin!

# Feature request

I don't like to populate my `package.json` with many configurations of different tools. I prefer to keep them separate or in CLI command.

So, can you add option to specify another source of configuration? For example, separate file, CLI arguments or something else.

Thank you!

**Comment by elwin013** [comment]
Parcel v1 is not maintained anymore - there will be no further development of this plugin, but some bug fixes (if any). 

Thank you all for your contributions! :smile:
