### ISSUE TITLE
Does not watch the static folder

### ISSUE THREAD

**Issue by ravilution** [elwin013/parcel-plugin-static-files-copy#7]
The plugin **does not watch** updates to the static folder. It does not copy files after they are updates. In my case it was JSON files.

**Comment by doconix** [comment]
I implemented this and have a pull request posted. In the meantime you can:

`npm install -D https://github.com/doconix/parcel-plugin-static-files-copy`

**Comment by elwin013** [comment]
Fixed by #15. Thank you for your contribution @doconix! :-)
